apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: container-app-dev
resources:
  - ../../base
  - ingress.yaml
images:
  - name: 
    newName: git.cocci.com:5050/<group>/<app>  ###  registry.gitlab.com/<group>/<project>/<image-1>
    newTag: v1.0.0
  - name: registry.gitlab.com/<group>/<project>/<image-2>
    newTag: v1.0.0
