apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-app-dev
  namespace: argocd
spec:
  source:
    repoURL: https://git.cocci.com/dev/ach-manager-argo.git
    targetRevision: HEAD
    path: apps/container-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: container-app-dev
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
